# EKG theme by Arim.
# Based on EKG theme by (sic!) -> sic@hybrid.art.pl

prompt %W<%%>%n
prompt2 %K<*>%n
error %R<!>%n
timestamp |%H:%M|

known_user %1
unknown_user %W[%n%W%1%n%W]%n
user_not_given %! %RMusisz podaæ u¿ytkownika%n\n
readline_prompt <%> 
readline_prompt_away <*> 
readline_prompt_invisible <.> 
readline_prompt_query [1;30m<[0m[1;37m%1[0m[1;30m>->[0m 
readline_more --<-- [1;37mnaci¶nij [enter][0m -->--

not_enough_params %! %RZa ma³o parametrów%n\n

unknown_command %! %RNieznane polecenie%n%W:%n %W%0%1%n\n
saved %> %WUstawienia zapisane.%n\n
error_saving %! %RWyst±pi³ b³ad podczas zapisu konfiguracji%n\n
error_reading_config %! %RWyst±pi³ b³±d odczytu pliku z konfiguracj±%n\n
quit %> %KNo to cze¶æ...%n\n\n
quit_descr %> %KNo to cze¶æ...%n%W%1%n\n\n
help %) %W%1%2%n %R->%n %3\n
help_more %) %1\n

message_header %K+------------%n Mesg from %W%1%n %c(%C%#%c/%2)%n %K------------%n\n
message_footer %K+------------%n\n
message_line %K|%n %1\n
message_line_width 72
chat_header %W+------------%n Chat with %W%1%n %c(%C%#%c/%2)%n %W------------%n\n
chat_footer %W+------------%n\n
chat_line %W|%n %1\n
chat_line_width 72
sysmsg_header %R+----------------%n Gadu-gadu system message %R----------------%n\n
sysmsg_footer %R+------------%n\n
sysmsg_line %R|%n %1\n
sysmsg_line_width 72

theme_loaded %> %WTemat wczytany.%n %K(C) Arim%n\n
theme_default %> %WUstawiono domy¶lny wygl±d.%n\n
error_loading_theme %! %R£adowanie tematu nie powiod³o siê!%n\n

user_info %)       %KPseudonim%n%W:%n %W%3%n\n%)           %KNumer%n%W:%n %W%7%n\n%)            %KStan%n%W:%n %8\n%) %KImiê i nazwisko%n%W:%n %1 %2\n%)  %KNumer telefonu%n%W:%n %5\n
user_info_avail %gdostêpny%n
user_info_avail_descr %gdostêpny%n [%1]
user_info_busy %czajêty%n
user_info_busy_descr %czajêty%n [%1]
user_info_not_avail %Kniedostêpny%n
user_info_not_avail_descr %Kniedostêpny%n [%1]
user_info_invisible %mniewidoczny%n
 
modify_done %> %WDane zmienione%n\n

search_results_single_active %G*%n
search_results_single_inactive %r!%n
search_results_single_female %MK%n
search_results_single_male %BM%n

search_results_single %W%7%n%W%[-10]1%n %K|%n %[12]3 %K|%n %6 %K|%n %[20]2 %K|%n %[4]5 %K|%n %c%[16]4%n\n

already_searching %> %RPrzeszukiwanie w toku%n %WWpisz:%n %yfind -stop%n %Waby przerwaæ...%n\n
search_failed %! %RB³±d podczas przeszukiwania%n%W: %1%n\n
search_not_found %! %RNie znaleziono nikogo o takich danych%n\n

list_empty %> %WTwoja lista jest pusta%n\n
list_avail %gdostêpny%n%K...%n   %W<%n%G+%n%W>%n   %g%[12]1%n |%K%[,-15]3%n|\n
list_avail_descr %gdostêpny%n%K...%n   %W<%n%G+%n%W>%n   %g%[12]1%n |%K%[,-15]3%n| %K[%5]%n\n
list_busy %czajêty%n%K.....%n   %W<%n%C?%n%W>%n   %c%[12]1%n |%K%[,-15]3%n|\n
list_busy_descr %czajêty%n%K.....%n   %W<%n%C?%n%W>%n   %c%[12]1%n |%K%[,-15]3%n| %K[%5]%n\n
list_not_avail %Kniedostêpny%n   %W<%n%R-%n%W>%n   %K%[12]1%n |%K...............%n|\n
list_not_avail_descr %Kniedostêpny%n   %W<%n%R-%n%W>%n   %K%[12]1%n |%K...............%n| %K[%5]%n\n
list_invisible %mniewidoczny%n   %W<%n%M*%n%W>%n   %m%[12]1%n |%K...............%n|\n

away %c%#%n %> %CWracam za chwilê ... %n\n
away_descr %c%#%n %> %CWracam za chwilê: %1%n\n
back %c%#%n %> %GJestem z powrotem %n\n
back_descr %c%#%n %> %GJestem z powrotem: %1%n\n
invisible %c%#%n %> %MJestem niewidzialny :)%n\n
invisible_descr %c%#%n %> %MJestem niewidzialny: %1%n\n
auto_away %c%#%n %> %CPo%n %W%1%n %Crobiê sobie przerwê%n\n
auto_away_descr %c%#%n %> %CPo%n %W%1%n %Crobiê sobie przerwê: %2%n\n

status_avail %c%#%n %> %g%[12]1%n%W<%n%G+%n%W>%n   %gdostêpny%n \n
status_avail_descr %c%#%n %> %g%[12]1%n%W<%n%G+%n%W>%n   %gdostêpny%n    %K[%3]%n \n
status_busy %c%#%n %> %c%[12]1%n%W<%n%C?%n%W>%n   %czajêty%n\n
status_busy_descr %c%#%n %> %c%[12]1%n%W<%n%C?%n%W>%n   %czajêty%n      %K[%3]%n \n
status_not_avail %c%#%n %> %K%[12]1%n%W<%n%R-%n%W>%n   %Kniedostêpny%n\n
status_not_avail_descr %c%#%n %> %K%[12]1%n%W<%n%R-%n%W>%n   %Kniedostêpny%n %K[%3]%n \n
status_invisible %c%#%n %> %M%[12]1%n%W<%n%M*%n%W>%n   %Mniewidoczny%n \n

show_status %> %WTwój status:%n %W%1%n %2\n
show_status_avail %W<%n%G+%n%W>%n  %gdostêpny%n
show_status_avail_descr %W<%n%G+%n%W>%n  %gdostêpny: %1%n
show_status_busy %W<%n%C?%n%W>%n  %Czajêty%n
show_status_busy_descr %W<%n%C?%n%W>%n  %Czajêty: %1%n
show_status_invisible %W<%n%M*%n%W>%n  %Mniewidoczny%n
show_status_invisible_descr %W<%n%M*%n%W>%n  %Mniewidoczny: %1%n
show_status_not_avail %W<%n%R-%n%W>%n  %Rniedostêpny%n
show_status_private_on %K[%n%Btylko dla przyjació³%n%K]%n
show_status_private_off 

private_mode_is_on %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n w³±czony\n
private_mode_is_off %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n wy³±czony\n
private_mode_on %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n w³±czono\n
private_mode_off %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n wy³±czono\n
private_mode_invalid %! Nieprawid³owa warto¶æ\n

ack_queued %) %K ack/%1 (%#) -queued-%n\n
ack_delivered %) %K ack/%1 (%#)%n\n

sms_sent %> %GSms dostarczony do u¿ytkownika %n %W%1%n\n
sms_failed %! %RSms do u¿ytkownika%n %W%1%n %Rnie zosta³ dostarczony!%n\n
sms_error %! %RB³±d podczas wysy³ania sms'a!%n\n
sms_unknown %! %W%1%n %Rnie ma podanego numeru we wpisie%n\n

variable %> %K%[_20]1%n%W%2%n\n
variable_not_found %! %RNieznana zmienna%n%W:%n %K[%n%W%1%n%K]%n\n
variable_invalid %! %Wset:%n %r[%1]%n <- z³a warto¶æ.\n

ignored_list %> ig: %1\n
ignored_list_empty %> %WLista ignorów jest pusta%n\n
ignored_added %> %WOd teraz ignorujesz%n %W%1%n\n
ignored_deleted

invalid_uin %! %RNiew³a¶ciwy numer%n %Wuin%n\n
user_added %> %WU¿ytkownik %K%1%n %Wzosta³ dodany%n\n
user_not_found %! %RNie ma na li¶cie u¿ytkownika %W%1%n\n
user_deleted %> %WU¿ytkownik%n %K%1%n %Wzosta³ usuniêty%n\n
user_exists %! %WU¿ytkownik%n %K%1%n %Wju¿ istnieje%n\n

error_adding %! %RB³±d podczas dodawania u¿ytkownika%n\n
error_deleting %! %RU¿ytkownika nie ma na li¶cie%n\n
error_adding_ignored %! %RPodany wpis ju¿ istnieje%n\n
error_not_ignored %! %RPodana osoba nie jest ignorowana%n\n

conn_broken %! %c%#%n %W---/%n%r*%n%W/---%n %RPo³±czenie z serwerem przerwane%n\n
connecting %> %WTrwa ³±czenie z serwerem...%n\n
during_connect %! %W£±czenie w toku...%n %k%xProszê czekaæ%n \n
connected %c%#%n %> [%G OK %n] %W<-%n %GPo³±czono z serwerem%n\n
conn_failed %! %BB³±d podczas ³±czenia:%n %W%1%n\n
conn_stopped %! %B£±czenie przerwane!%n\n
conn_timeout %! %BSerwer nie odpowiada. Spróbuj jeszcze raz.%n\n
disconnected %> %c%#%n %WRoz³±czono%n %R---| |---%n\n
disconnected_descr %> %c%#%n %WRoz³±czono: %1%n %R---| |---%n\n
disconn_warning %! %BRoz³±czono nas.%n\n
not_connected %! %RNie jeste¶ po³±czony z serwerem%n\n
already_connected %! %RJu¿ jeste¶ po³±czony!%n\n
offline_mode %> %WJeste¶ w tybie off-line!%n\n

error_reading_config %! %RB³±d podczas czytania pliku konfiguracyjnego%n\n

aliases_list %> %W%[8]1%n %K->%n %g%2%n\n
aliases_add %> %YDodano alias%n %W%1%n %C->%n %W%2%n\n
aliases_del %> %YAlias %W%1%n %Yzosta³ usuniêty%n\n
aliases_exist %! %RAlias %W%1%n %Rju¿ istnieje%n\n
aliases_noexist %! %RAlias %W%1%n %Rnie istnieje%n\n
aliases_list_empty %> %YBrak aliasów%n\n
aliases_invalid %! %RNiew³a¶ciwy parametr%n %C(help alias?)%n\n

sms_msg EKG: %# msg %1: %2
sms_chat EKG: %# chat %1: %2

quick_list %) %gobecny%W/%czajêty%W/%Mniewidzialny%n\n%)%1\n
quick_list_avail  %g%1%n
quick_list_busy  %c%1%n
quick_list_invisible  %M%1%n

ekg_version %) EKG - Eksperymentalny Klient Gadu-Gadu (%W%1%n)\n%) Temat (C) 2002 by Arim.\n\n
