# Based on EKG theme by (Arim)
# EKG theme by DJ.

ack_delivered %) %#: %K ack/%1%n\n
ack_queued %) %#: %K ack/%1 -queued-%n\n
aliases_add %> %WDodano alias %Y%1%n\n
aliases_append %> %WDodano do aliasu %Y%1%n\n
aliases_del %> %WAlias %Y%1 %Wzosta³ usuniêty%n\n
aliases_exist %! %RAlias %W%1%n %Rju¿ istnieje%n\n
aliases_invalid %! %RNiew³a¶ciwy parametr%n %C(help alias?)%n\n
aliases_list %> %W%[8]1%n %K->%n %g%2%n\n
aliases_list_empty %> %WBrak aliasów%n\n
aliases_list_next %> %[8]3 %K=>%n %g%2%n\n
aliases_noexist %! %RAlias %W%1%n %Rnie istnieje!%n\n
already_connected %! %RJu¿ jeste¶ po³±czony!%n\n
already_searching %> %RPrzeszukiwanie w toku%n %WWpisz:%n %yfind -stop%n %Waby przerwaæ...%n\n
auto_away %> %c%#%n: %CPo%n %W%1%n %Crobiê sobie przerwê%n\n
auto_away_descr %> %c%#%n: %CPo%n %W%1%n %Crobiê sobie przerwê: %2%n\n
autosaved %> %WNast±pi³ autozapis ustawieñ.\n
away %> %c%#%n: %cWracam za chwilê ... %n\n
away_descr %> %c%#%n: %cWracam za chwilê: %1%n\n
back %> %c%#%n: %gJestem z powrotem %n\n
back_descr %> %c%#%n: %gJestem z powrotem: %1%n\n
change %> %WZmieni³e¶ informacje w katalogu publicznym.%n\n
change_failed %! %RB³±d podczas zmiany informacji w katalogu publicznym!%n\n
change_not_enough_params %! %RPolecenie wymaga podania %Wwszystkich%n %Rparametrów!%n\n
change_timeout %! %RPrzekroczono limit czasu operacji zmiany katalogu publicznego!%n\n
chat_line_first %Y%#%W:%g%[,10]2%W:%n %1\n
chat_conference_line_first %Y%#%W:%g%[,10]2%W:%n %1\n
chat_line       %1\n
conn_broken %! %c%#%n: %W---/%n%r*%n%W/---%n %RPo³±czenie z serwerem przerwane%n\n
conn_failed %! %BB³±d podczas ³±czenia:%n %W%1%n\n
conn_stopped %! %B£±czenie przerwane!%n\n
conn_timeout %! %BSerwer nie odpowiada. Spróbuj jeszcze raz.%n\n
connected %> %c%#%n [%G OK %n] %W<-%n %GPo³±czono z serwerem%n\n
connecting %> %WTrwa ³±czenie z serwerem...%n\n
disconn_warning %! %BRoz³±czono nas.%n\n
disconnected %> %c%#%n: %WRoz³±czono%n %R---| |---%n\n
disconnected_descr %> %c%#%n: %WRoz³±czono: %1%n %R---| |---%n\n
during_connect %! %W£±czenie w toku...%n %k%xProszê czekaæ%n \n
ekg_version %) EKG - Eksperymentalny Klient Gadu-Gadu (%W%1%n)\n%) Temat (C) 2002 by dj.\n\n
error %K:%r:%R:%n
error_adding %! %RB³±d podczas dodawania u¿ytkownika%n\n
error_adding_ignored %! %RPodany wpis ju¿ istnieje%n\n
error_deleting %! %RU¿ytkownika nie ma na li¶cie%n\n
error_loading_theme %! %R£adowanie tematu %W%1 %Rnie powiod³o siê!%n\n
error_not_ignored %! %RPodana osoba nie jest ignorowana%n\n
error_reading_config %! %RWyst±pi³ b³±d odczytu pliku z konfiguracj±: %W%1%n\n
error_saving %! %RWyst±pi³ b³ad podczas zapisu konfiguracji!%n\n
help %) %W%1%2%n %R->%n %3\n
help_more %) %1\n
ignored_added %> %WOd teraz ignorujesz%n %Y%1%n\n
ignored_deleted %> %WOd teraz przestajesz ignorowaæ %Y%1%n\n
ignored_list %> ig: %1\n
ignored_list_empty %> %WLista ignorów jest pusta%n\n
invalid_uin %! %RNiew³a¶ciwy numer%n %Wuin%n\n
invisible %> %c%#%n: %MJestem niewidzialny :)%n\n
invisible_descr %> %c%#%n: %MJestem niewidzialny: %1%n\n
known_user %1
list_avail %> %gdostêpn%@2%n%K...%n   %W<%n%G+%n%W>%n   %g%[12]1%n |%K%[,-15]3%n|\n
list_avail_descr %> %gdostêpn%@2%n%K...%n   %W<%n%G+%n%W>%n   %g%[12]1%n |%K%[,-15]3%n| %K[%5]%n\n
list_busy %> %czajêt%@2%n%K.....%n   %W<%n%C?%n%W>%n   %c%[12]1%n |%K%[,-15]3%n|\n
list_busy_descr %> %czajêt%@2%n%K.....%n   %W<%n%C?%n%W>%n   %c%[12]1%n |%K%[,-15]3%n| %K[%5]%n\n
list_empty %> %WTwoja lista jest pusta%n\n
list_invisible %> %mniewidoczn%@2%n   %W<%n%M*%n%W>%n   %m%[12]1%n |%K...............%n|\n
list_invisible_descr %> %mniewidoczn%@2%n   %W<%n%M-%n%W>%n   %m%[12]1%n |%K...............%n| %K[%5]%n\n
list_not_avail %> %Kniedostêpn%@2%n   %W<%n%R-%n%W>%n   %K%[12]1%n |%K...............%n|\n
list_not_avail_descr %> %Kniedostêpn%@1%n   %W<%n%R-%n%W>%n   %K%[12]1%n |%K...............%n| %K[%5]%n\n
message_line_first %Y%#%W:%G%[,10]2%W:%n %1\n
message_conference_line_first %Y%#%W:%G%[,10]2%W:%n %1\n
message_line       %1\n
modify_done %> %WDane zmienione%n\n
not_connected %! %RNie jeste¶ po³±czony z serwerem!%n\n
not_enough_params %! %RZa ma³o parametrów%n\n
not_implemented %! %RTej funkcji jeszcze nie ma!%n\n
offline_mode %> %WJeste¶ w tybie off-line!%n\n
passwd %> %WHas³o zosta³o zmienione.%n\n
passwd_failed %! %RB³±d podczas zmiany has³a!%n\n
passwd_timeout %! %RPrzekroczono limit czasu operacji zmiany has³a!%n\n
private_mode_invalid %! Nieprawid³owa warto¶æ\n
private_mode_is_off %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n wy³±czony\n
private_mode_is_on %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n w³±czony\n
private_mode_off %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n wy³±czono\n
private_mode_on %> %K[%n%Btylko dla przyjació³%n%K]%n%W:%n w³±czono\n
prompt %K:%g:%G:%n
prompt2 %K:%c:%C:%n
quick_list %) %gobecny%W/%czajêty%W/%Mniewidzialny%n\n%)%1\n
quick_list_avail  %g%1%n
quick_list_busy  %c%1%n
quick_list_invisible  %M%1%n
quit %> %KNo to cze¶æ...%n\n\n
quit_descr %> %KNo to cze¶æ...%n%W%1%n\n\n
readline_more --<-- [1;37mnaci¶nij [enter][0m -->--
readline_prompt <%> 
readline_prompt_away <*> 
readline_prompt_invisible <.> 
readline_prompt_query <%1>-> 
readline_prompt_win <%% win.%1> 
readline_prompt_away_win <* win.%1> 
readline_prompt_invisible_win <. win.%1> 
readline_prompt_query_win <%1/win.%2>-> 
register_failed %! %RB³±d podczas rejestracji%n\n
register_pending %! %RRejestracja w toku%n\n
register_timeout %! %RPrzekroczono limit czasu operacji rejestrowania%n\n
registered_today %! %RJu¿ zarejestrowano jeden numer. Nie nadu¿ywaj.%n\n
remind %> %WHas³o zosta³o wys³ane.%n\n
remind_failed %! %RB³±d podczas wysy³ania has³a%n\n
remind_timeout %! %RPrzekroczono limit czasu operacji wys³ania has³a%n\n
saved %> %WUstawienia zapisane.%n\n
search_failed %! %RB³±d podczas przeszukiwania%n%W: %1%n\n
search_not_found %! %RNie znaleziono nikogo o takich danych%n\n
search_results_multi %> %W%7%[-10]1%n %K|%n %[10]3 %K|%n %6 %K|%n %[18]2 %K|%n %[4]5 %K|%n %c%[14]4%n\n
search_results_multi_active %W<%G+%W>%n
search_results_multi_busy %W<%C?%W>%n
search_results_multi_inactive %W<%R-%W>%n
search_results_multi_female %MK%n
search_results_multi_male %BM%n
search_results_multi_unknown -
search_results_single %> %W%7%[-10]1%n %K|%n %[10]3 %K|%n %6 %K|%n %[18]2 %K|%n %[4]5 %K|%n %c%[14]4%n\n
search_results_single_active %W<%G+%W>%n
search_results_single_busy %W<%C?%W>%n
search_results_single_female %MK%n
search_results_single_inactive %W<%R-%W>%n
search_results_single_male %BM%n
search_results_single_unknown %Wbrak%n
search_stopped %) Nie to nie. Dalej nie szukam.\n
search_timeout %! %RPrzekroczono limit czasu operacji szukania!%n\n
show_status %> %WTwój status:%n %1 %2\n%> %WJeste¶ zalogowany na serwerze %g%3%W.%n\n
show_status_avail %W<%n%G+%n%W>%n  %gdostêpny%n
show_status_avail_descr %W<%n%G+%n%W>%n  %gdostêpny: %1%n
show_status_busy %W<%n%C?%n%W>%n  %Czajêty%n
show_status_busy_descr %W<%n%C?%n%W>%n  %Czajêty: %1%n
show_status_invisible %W<%n%M*%n%W>%n  %Mniewidoczny%n
show_status_invisible_descr %W<%n%M*%n%W>%n  %Mniewidoczny: %1%n
show_status_not_avail %W<%n%R-%n%W>%n  %Rniedostêpny%n
show_status_private_off 
show_status_private_on %K[%n%Btylko dla przyjació³%n%K]%n
sms_chat EKG: %# chat %1: %2
sms_error %! %RB³±d podczas wysy³ania sms'a!%n\n
sms_failed %! %RSms do u¿ytkownika%n %W%1%n %Rnie zosta³ dostarczony!%n\n
sms_msg EKG: %# msg %1: %2
sms_sent %> %GSms dostarczony do u¿ytkownika %n %W%1%n\n
sms_unknown %! %W%1%n %Rnie ma podanego numeru we wpisie%n\n
status_avail %> %c%#%n: %g%[12]1%n%W<%n%G+%n%W>%n   %gdostêpn%@2%n \n
status_avail_descr %> %c%#%n: %g%[12]1%n%W<%n%G+%n%W>%n   %gdostêpn%@2%n    %K[%3]%n \n
status_busy %> %c%#%n: %c%[12]1%n%W<%n%C?%n%W>%n   %czajêt%@2%n\n
status_busy_descr %> %c%#%n: %c%[12]1%n%W<%n%C?%n%W>%n   %czajêt%@2%n      %K[%3]%n \n
status_invisible %> %c%#%n: %M%[12]1%n%W<%n%M*%n%W>%n   %Mniewidoczn%@2%n \n
status_invisible_descr %> %c%#%n: %M%[12]1%n%W<%n%M*%n%W>%n   %Mniewidoczn%@2%n %K[%3]%n \n
status_not_avail %> %c%#%n: %K%[12]1%n%W<%n%R-%n%W>%n   %Kniedostêpn%@2%n\n
status_not_avail_descr %> %c%#%n: %K%[12]1%n%W<%n%R-%n%W>%n   %Kniedostêpn%@2%n %K[%3]%n \n
theme_default %> %WUstawiono domy¶lny wygl±d.%n\n
theme_loaded %> %WTemat wczytany.%n\n
timestamp %H:%M
unknown_command %! %RNieznane polecenie%n%W:%n %W%0%1%n\n
unknown_user %1
user_added %> %WU¿ytkownik %K%1%n %Wzosta³ dodany%n\n
user_deleted %> %WU¿ytkownik%n %K%1%n %Wzosta³ usuniêty%n\n
user_exists %! %WU¿ytkownik%n %K%1%n %Wju¿ istnieje%n\n
user_info %)       %KPseudonim%n%W:%n %W%3%n\n%)           %KNumer%n%W:%n %W%7%n\n%)            %KStan%n%W:%n %8\n%) %KImiê i nazwisko%n%W:%n %1 %2\n%)  %KNumer telefonu%n%W:%n %5\n
user_info_avail %gdostêpn%@1%n
user_info_avail_descr %gdostêpn%@1%n [%2]
user_info_busy %czajêt%@1%n
user_info_busy_descr %czajêt%@1%n [%2]
user_info_invisible %mniewidoczn%@1%n
user_info_not_avail %Kniedostêpn%@1%n
user_info_not_avail_descr %Kniedostêpn%@1%n [%2]
user_not_found %! %RNie ma na li¶cie u¿ytkownika %W%1%n!\n
user_not_given %! %RMusisz podaæ u¿ytkownika!%n\n
userlist_get_error %! %RB³±d podczas pobierania listy kontaktów!%n\n
userlist_get_ok %) %WListê kontaktów wczytano z serwera.%n\n
userlist_put_error %! %RB³±d podczas wysy³ania listy kontaktów!%n\n
userlist_put_ok %) %WListê kontaktów zachowano na serwerze.%n\n
variable %> %K%[_20]1%n%W%2%n\n
variable_invalid %! %Wset:%n %r[%1]%n <- z³a warto¶æ.\n
variable_not_found %! %RNieznana zmienna%n%W:%n %K[%n%W%1%n%K]%n\n
sent_line_first %Y%#%W:%m%[,10]2%W:%n %1\n
sent_conference_line_first %Y%#%W:%m%[,10]2%W:%n %1\n
sent_line       %1\n
