# eileen.theme (c) by en 2002;
# still `underconstruction`

# TIME
timestamp %H.%M
theme_loaded %> %Ren%w.%rtheme%n %K(c)2002::en_at_irc.pl%n\n
welcome %> \n%Rekg:wersja:%1%r (loaded en.theme)%n\n\n
ekg_version %) %Rekg:%r(%W%1%n%r) %Rlibgadu-%1 %r(%Rprotokó³ %W%2%r, %Rklient %W%3%r)%n\n
autosaved %> %KZapisano\n

quit \n%Kbye...%n\n%n

# USERS
known_user %1%K.%K%[.7]2

# PROMPT

prompt %K÷%n
prompt2	%W÷%n

error %Y§ %Yo%yo:%n

readline_prompt [31;6m .o[31;1mo: [0m
readline_prompt_query [31;6m<@:[31;1m%1[0m[31;6m> [0m
readline_prompt_away [31;6m .z[31;1mz: [0m
readline_prompt_invisible [31;6m .i[31;1mv: [0m
readline_prompt_win [31;6m[%1] .o[31;1mo: [0m
readline_prompt_query_win [31;6m<%2:[31;1m%1[0m[31;6m> [0m
readline_prompt_away_win [31;6m[%1] .z[31;1mz[31;6m:[31;6m [0m
readline_prompt_invisible_win [31;6m[%1] .i[31;1mv: [0m
readline_prompt_win_act [31;6m[%1[31;6m#[37;1m%2[0m[31;6m] .o[31;1mo[31;6m: [0m
readline_prompt_query_win_act [31;6m<%2#[37;1m%3[0m[31;6m:[31;1m%1[31;6m> [0m
readline_prompt_away_win_act [31;6m[%1#[37;1m%2[0m[31;6m] .z[31;1mz[31;6m: [0m
readline_prompt_invisible_win_act [31;6m[%1#[37;1m%2[0m[31;6m] .i[31;1mv: [0m

readline_more [37;1m÷ ----wiêcej---- \n[0m

# LIST

list_avail %> %K:%n %G%[-40]1 %g:%Go%g:%n %K[%3]%n\n
list_avail_descr %> %K:%n %G%[-40]1 %g:%Go%g:%n %K[%3]%n\n
list_busy %> %K:%n %g%[-40]1 %K:%go%K:%n %K[%3] %n\n
list_busy_descr %> %K:%n %g%[-40]1 %K:%go%K:%n %K[%3] %n\n
list_not_avail %> %K.%n %K%[-40]1 %K:.:%n\n
list_not_avail_descr %> %K.%n %K%[-40]1 %K:.:%n\n
list_unknown %> %K.%n %R%[-40]1 %K:?:%n\n

# CHAT

chat_header %W÷%G-> %gchat%G@%g%1 %g÷ %K%2%n\n
chat_line %g:  %n %1\n
chat_footer %g:%n\n
chat_line_width -8
chat_timestamp %H:%M %Y+%m+%d 

# MSG

message_header %W÷%G-> %Wmsg%G@%g%1n\n
message_line %W.  %n %1\n
message_line_width -8
message_footer %W.%n\n
message_timestamp %H:%M %Y+%m+%d

# SENT

sent_header %R<-%W÷ %rsent%R@ %R÷ %r%2 %n\n
sent_footer %r:%n\n
sent_line %r:   %1%n\n
sent_line_width -8
sent_timestamp %H.%M %Y+%m+%d


# SYSTEM

not_enough_params %! %KZa ma³o parametrów -> %Whelp %1%n\n
invalid_uin %! %KNie ma takiego numeru :S\n
user_not_found %! %K%1? Nie znaleziono%n\n
not_implemented %! %K Nie zaimplementowane\n
unknown_command %! %KNieznane polecenie %1%n\n
group_empty %! Grupa %T%1%n jest pusta\n
user_exists %! %K%1 ju¿ istnieje w li¶cie kontaktów\n
error_adding %! %KB³±d podczas dopisywania do listy kontaktów\n
error_deleting %! %KB³±d podczas usuwania z listy kontaktów\n
descr_too_long %! %KD³ugo¶æ opisu przekracza limit, uciêtych znaków: %1%n\n
error_adding_ignored %! %KB³±d podczas dodawania do listy ignorowanych\n
error_not_ignored %! %K%1 nie jest na li¶cie ignorowanych\n
ignored_list_empty %! %KLista ignorowanych u¿ytkowników jest pusta\n

secure %W{szyfrowane}%n

user_added %> %KDopisano %1 do listy kontaktów\n
user_deleted %> %KUsuniêto %1 z listy kontaktów\n
away %> %K.%no%WO %Caway%n\n
away_descr %> %K.%no%WO %Caway%c %1.%2%n\n
back %> %K.%no%WO %Cdostêpny%n\n
back_descr %> %K.%no%WO %Cdostêpny -> %c%1.%2%n\n
invisible %> %K.%no%WO %Cukryty%n\n
invisible_descr %> %K.%no%WO %Cukryty ->%n %c%1%n%2\n
private_mode_is_on %> %K.%no%WO %rprivate -> %Ron%n\n
private_mode_is_off %> %K.%no%WO %rprivate -> %Roff%n\n
private_mode_on %> %K.%no%WO %rprivate -> %Ron%n\n
private_mode_off %> %K.%no%WO %rprivate -> %Ron%n\n
private_mode_invalid %! %KNieprawid³owa warto¶æ\n
help %> %R%1%r%2 - %3%4\n
help_footer  \n%> %KGwiazdka (%n*%K) oznacza, ¿e mo¿na uzyskaæ wiêcej szczegó³ów%n\n\n
help_quick %> %KWiêcej informacji -> %n"docs/ULOTKA"%K lub %nhttp://ekg.chmurka.net/%K.\n\n$

help_more %) %K%1%n\n
help_alias %) %K%1 jest aliasem%n\n

