.TH EKG n "31 pa¼dziernik 2001" 
.SH NAZWA
ekg \- Eksperymentalny Klient Gadu-Gadu
.SH SK£ADNIA
.B ekg [
.BI opcje
.B ]

.SH OPIS
.B ekg
Jest to eksperymentalny klient Gadu-Gadu.

.SH OPCJE
.TP
.BI \-d\ [\-\-debug]
W³±cza tryb "debug" - jest to specjalny tryb, pokazuj±cy, co robi 
program w danej chwili.
.TP
.BI \-n\ [\-\-no-auto]
Nie ³±cz siê automagicznie. Po uruchomieniu nie ³±czy siê automatycznie 
z serwerami gg. 
.TP
.BI \-u "\ " username\ [\-\-user \ username]
Zezwala na uruchomienie ekg z innym \"u¿ytkownikiem\". 
Standardowo konfiguracja ekg znajduje sie w katalogu ~/.gg - Ta 
opcja pozwala na stworzenie struktury podkatalogów z oddzielnymi 
konfiguracjami.
.TP
.BI \-t\ theme\ [\-\-theme\ theme]
³aduje opis wygl±du z podanego pliku
.TP
.BI \-a\ [\-\-away]
po po³±czeniu zmienia stan na ,,zajêty''
.TP
.BI \-b\ [\-\-back]
po po³±czeniu zmienia stan na ,,dostêpny''
.TP 
.BI \-i\ [\-\-invisible]
po po³±czeniu zmienia stan na ,,niewidoczny''
.TP
.BI \-p\ [\-\-private]
po po³±czeniu zmienia stan na ,,tylko dla przyjació³''
