#!/bin/sh
# skrypt uruchamiaj±cy ekg pod kontrol± valgrinda. przydatny tylko
# developerom. w snapshotach go nie ma.
valgrind --num-callers=10 --leak-check=yes --show-reachable=yes ./ekg "$@" 2> ekg.log
